language: python

cache:
  directories:
  - $HOME/.cache/pip

install:
  - 'pip install -r requirements.txt'
  - 'pip install -r test-requirements.txt'

script:
  - 'flake8 --ignore=F403 .'
  - 'py.test tests'

matrix:
  include:
    - python: '2.7'

notifications:
  email: false

git:
  depth: 3

sudo: false